profiles:
- name: "Linux Qt5.5.1 GCC 4.9"
  platform: Linux
  commands: std
  setup: ['qt551_gcc49']

- name: "Linux Qt5.5.1 GCC 4.9 QBS 1.7.1"
  platform: Linux
  commands: qbs
  setup: ['qbs171_qt551_gcc49']

- name: "Linux Qt5.5.1 GCC 5.4"
  platform: Linux
  commands: std
  setup: ['qt551_gcc54']

- name: "Linux Qt5.5.1 GCC 5.4 QBS 1.7.1"
  platform: Linux
  commands: std
  setup: ['qbs171_qt551_gcc54']

- name: "Windows Qt5.4 MinGW 4.9.1"
  platform: Windows
  commands: mingw
  setup: ['qt54_mingw491']

- name: "Windows Qt5.5.1 MingGW 4.9.2"
  platform: Windows
  commands: mingw
  setup: ['qt551_mingw492']

- name: "Windows Qt5.5 MSVC 2012 x32"
  platform: Windows
  commands: msvc
  setup: ['qt55_msvc2012']

- name: "Windows Qt5.5 MSVC 2013 x64"
  platform: Windows
  commands: msvc
  setup: ['qt55_msvc2013_x64']

actions:
- name: Prepare
  std: 'qmake -r'
  msvc: 'qmake -r'
  mingw: 'qmake -r'
  qbs: "echo 'No QBS Prepare'"

- name: Build
  std: 'make'
  msvc: 'nmake.exe'
  mingw: 'mingw32-make.exe'
  qbs: 'qbs'

- name: Test
  std: 'make check'
  msvc: 'nmake check'
  mingw: 'mingw32-make.exe check'
  qbs: "echo 'No QBS Test'"
